/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rest.panels;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rest.restaurante.Conexion;

/**
 *
 * @author HP
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        tiempo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCheckArrozR = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckEstofadoR = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckPolloH = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckChuleta = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckEncebollado = new javax.swing.JCheckBox();
        jCheckPescadoF = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jCheckContinental = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCheckFritada = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jCheckMote = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jCheckEstofadoP = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        btoConfInfo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        numero_orden = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelHora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNum = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrden = new javax.swing.JTable();
        btoNuevaOrd = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelCorreo = new javax.swing.JLabel();
        btoConfirmarM = new javax.swing.JButton();

        jLabel20.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel20.setText("2.50$");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/estofadoRes.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        jCheckArrozR.setEnabled(false);
        jCheckArrozR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckArrozRActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel7.setText("Arroz Relleno");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/arrozRelleno.jpg"))); // NOI18N
        jLabel8.setText("jLabel6");

        jCheckEstofadoR.setEnabled(false);
        jCheckEstofadoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckEstofadoRActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel4.setText("Estofado de Res");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/PolloHornado.jpg"))); // NOI18N
        jLabel9.setText("jLabel6");

        jCheckPolloH.setEnabled(false);
        jCheckPolloH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckPolloHActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel5.setText("Pollo Hornado");

        jCheckChuleta.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jCheckChuleta.setEnabled(false);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/Chuleta.jpg"))); // NOI18N
        jLabel10.setText("jLabel6");

        jLabel11.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel11.setText("Chuleta");

        jLabel13.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel13.setText("Encebollado");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/encebollado.jpg"))); // NOI18N
        jLabel14.setText("jLabel6");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/pescadoFrito.jpg"))); // NOI18N
        jLabel15.setText("jLabel6");

        jLabel16.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel16.setText("Pescado Frito");

        jCheckEncebollado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckEncebolladoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel17.setText("2.50$");

        jLabel18.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel18.setText("3.00$");

        jLabel19.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel19.setText("2.50$");

        jLabel21.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel21.setText("2.50$");

        jLabel22.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel22.setText("3.00$");

        jLabel23.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel23.setText("3.50$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckChuleta)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckEncebollado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckArrozR)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckEstofadoR, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckPolloH, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckPescadoF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(43, 43, 43))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addGap(103, 103, 103)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckEstofadoR)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckPolloH)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckArrozR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckPescadoF)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckChuleta)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckEncebollado))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Comida", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/Fritada.jpg"))); // NOI18N
        jLabel24.setText("jLabel6");

        jCheckContinental.setEnabled(false);
        jCheckContinental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckContinentalActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel25.setText("Continental");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/Continental.jpg"))); // NOI18N
        jLabel26.setText("jLabel6");

        jCheckFritada.setEnabled(false);
        jCheckFritada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckFritadaActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel27.setText("Fritada");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/motePillo.png"))); // NOI18N
        jLabel28.setText("jLabel6");

        jCheckMote.setEnabled(false);
        jCheckMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMoteActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel29.setText("Mote ");

        jCheckEstofadoP.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jCheckEstofadoP.setEnabled(false);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest/imagenes/pollo.jpg"))); // NOI18N
        jLabel30.setText("jLabel6");

        jLabel31.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel31.setText("Estofado de Pollo");

        jLabel36.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel36.setText("2.50$");

        jLabel37.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel37.setText("3.00$");

        jLabel38.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel38.setText("2.00$");

        jLabel39.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabel39.setText("2.50$");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckContinental)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 61, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckFritada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckEstofadoP)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 61, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckMote, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(143, 143, 143)
                .addComponent(jLabel29)
                .addGap(49, 49, 49))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckFritada)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckMote)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jCheckContinental)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckEstofadoP)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Desayunos", jPanel6);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del Cliente:");

        nombre.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jLabel2.setText("Numero de Orden:");

        correo.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N

        btoConfInfo.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        btoConfInfo.setText("Confirmar");
        btoConfInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoConfInfoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jLabel12.setText("Correo:");

        numero_orden.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numero_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(btoConfInfo))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btoConfInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Orden", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHora.setFont(new java.awt.Font("Roboto Condensed Light", 0, 12)); // NOI18N
        jLabelHora.setText("hora");
        jPanel2.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 37, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel3.setText("Hora:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, 37, -1));
        jPanel2.add(jLabelNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 193, 19));
        jPanel2.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 193, 19));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 10));

        jTableOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOrden);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 290));

        btoNuevaOrd.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        btoNuevaOrd.setText("Nueva Orden");
        btoNuevaOrd.setEnabled(false);
        btoNuevaOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoNuevaOrdActionPerformed(evt);
            }
        });
        jPanel2.add(btoNuevaOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, -1));
        jPanel2.add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 193, 19));

        btoConfirmarM.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        btoConfirmarM.setText("Confirmar");
        btoConfirmarM.setEnabled(false);
        btoConfirmarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoConfirmarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1)
                    .addComponent(btoConfirmarM, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btoConfirmarM)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void btoConfInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoConfInfoActionPerformed
        
        if(nombre.getText().equals("") && numero_orden.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Llene los datos..!");
        }else{
            jLabelNom.setText(nombre.getText());
            jLabelNum.setText("#" + numero_orden.getText());
            jLabelCorreo.setText(correo.getText());

            nombre.setEnabled(false);
            numero_orden.setEnabled(false);
            correo.setEnabled(false);
            nombre.setText("");
            numero_orden.setText("");
            correo.setText("");

            btoConfInfo.setEnabled(false);
            activarMenu(true);
            
        }
        
        
        
    }//GEN-LAST:event_btoConfInfoActionPerformed

    private void btoConfirmarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoConfirmarMActionPerformed

        if(jCheckArrozR.isSelected()){
            String data[] = {"Arroz Relleno", "2.50$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
        
        }if(jCheckEstofadoR.isSelected()){
            String data[] = {"Estofado de Res", "3.00$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
        
        }if(jCheckPolloH.isSelected()){
            String data[] = {"Pollo Hornado", "2.50$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
        
        }if(jCheckChuleta.isSelected()){
            String data[] = {"Chuleta", "2.50$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);

  
        }if(jCheckEncebollado.isSelected()){
            String data[] = {"Encebollado", "3.50$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
  
        }if(jCheckPescadoF.isSelected()){
            String data[] = {"Pescado Frito", "3.50$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
  
        }if(jCheckContinental.isSelected()){
            String data[] = {"Continental", "2.50$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
        
        }if(jCheckFritada.isSelected()){
            String data[] = {"Fritada", "3.00$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
  
        }if(jCheckMote.isSelected()){
            String data[] = {"Mote", "2.00$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
  
        }if(jCheckEstofadoP.isSelected()){
            String data[] = {"Estofado de Pollo", "2.50$"};
            DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();
            tblModel.addRow(data);
            
            activarMenu(false);
            btoNuevaOrd.setEnabled(true);
  
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione algo del Menú");
        }
        
    }//GEN-LAST:event_btoConfirmarMActionPerformed

    private void btoNuevaOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoNuevaOrdActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel)jTableOrden.getModel();

        for(int i = jTableOrden.getRowCount()-1; i >= 0; i--){
            tblModel.removeRow(i);
        }

        nombre.setEnabled(true);
        numero_orden.setEnabled(true);
        correo.setEnabled(true);
        btoConfInfo.setEnabled(true);
        btoNuevaOrd.setEnabled(false);
        jLabelNom.setText("");
        jLabelNum.setText("");
        jLabelCorreo.setText("");
        
    }//GEN-LAST:event_btoNuevaOrdActionPerformed

    private void jCheckMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckMoteActionPerformed

    private void jCheckFritadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckFritadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckFritadaActionPerformed

    private void jCheckContinentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckContinentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckContinentalActionPerformed

    private void jCheckEncebolladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckEncebolladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckEncebolladoActionPerformed

    private void jCheckPolloHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckPolloHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckPolloHActionPerformed

    private void jCheckEstofadoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckEstofadoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckEstofadoRActionPerformed

    private void jCheckArrozRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckArrozRActionPerformed

    }//GEN-LAST:event_jCheckArrozRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }
    public void tiempo(){
        Calendar fecha = new GregorianCalendar();
        String hora = Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
        int min = fecha.get(Calendar.MINUTE);
        
        String horaComple = hora + ":" + min;
        
        jLabelHora.setText(horaComple);
    }
    public void activarMenu(boolean editable){
        jCheckArrozR.setEnabled(editable);
        jCheckEstofadoR.setEnabled(editable);
        jCheckPolloH.setEnabled(editable);
        jCheckChuleta.setEnabled(editable);
        jCheckEncebollado.setEnabled(editable);
        jCheckPescadoF.setEnabled(editable);
        jCheckContinental.setEnabled(editable);
        jCheckFritada.setEnabled(editable);
        jCheckMote.setEnabled(editable);
        jCheckEstofadoP.setEnabled(editable);
        
        btoConfirmarM.setEnabled(editable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoConfInfo;
    private javax.swing.JButton btoConfirmarM;
    private javax.swing.JButton btoNuevaOrd;
    private javax.swing.JTextField correo;
    private javax.swing.JCheckBox jCheckArrozR;
    private javax.swing.JCheckBox jCheckChuleta;
    private javax.swing.JCheckBox jCheckContinental;
    private javax.swing.JCheckBox jCheckEncebollado;
    private javax.swing.JCheckBox jCheckEstofadoP;
    private javax.swing.JCheckBox jCheckEstofadoR;
    private javax.swing.JCheckBox jCheckFritada;
    private javax.swing.JCheckBox jCheckMote;
    private javax.swing.JCheckBox jCheckPescadoF;
    private javax.swing.JCheckBox jCheckPolloH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableOrden;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero_orden;
    // End of variables declaration//GEN-END:variables
}
